### ISSUE TITLE
Meeting Minutes

### ISSUE THREAD

**Issue by YikiSu** [UBC-MDS/aus_rain_cloud#1]
- [x] Everyone gives it a try for Milestone 1
- [x] Meet on Friday to compile the work and discuss
- [x] Aims to submit milestone 1 by Friday
- [x] Download the data
- [ ] Combine the data
- [ ] EDA by python - Yiki, Sukhdeep
- [ ] EDA by R - Jacob and Sang Yoon Lee
- [ ] Create your own branches and work from there
- [ ] Update the README - by Jacob
- [ ] Don't forget to include written explanations for your work
- [x] Team contract
- [X] Repository
- [ ] python notebook should be under notebooks folder

**Comment by sukh2929** [comment]
created notebooks folder and empty file inside it
